version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 0.0.0.0:18080:8080/tcp
    environment:
      PREFIX: /files